# Self-Hosted Github Action Runners on GCP via Cirun.io
# Reference: https://docs.cirun.io/Reference/yml.html
runners:
  - name: "gpu-runner"
    # Cloud Provider: GCP
    cloud: "gcp"
    # Cheapest GPU on GCP
    gpu: "nvidia-tesla-t4"
    # Cheapest VM on GCP, with GPU attachable
    instance_type: "n1-standard-1"
    # Ubuntu-20.4, can be seen from "gcloud compute images list"
    # machine_image: "ubuntu-2204-jammy"
    # machine_image: "common-dl-gpu-debian-10"
    machine_image: "c0-deeplearning-common-cu113-v20221215-debian-10"
    preemptible: false
    # Add this label in the "runs-on" param in .github/workflows/<workflow-name>.yml
    # So that this runner is created for running the workflow
    labels:
      - "cirun-gpu-runner"
